apis/urls.py
from . import views
from django.urls import path


app_name = "apis"

urlpatterns = [
  path("apis/search_key", views.SearchKeyView.as_view(), name="search_key"),
  path("apis/whatsapp", views.WhatsappView.as_view(), name="whatsapp"),
    
]

blog/urls.py
from . import views
from django.urls import path


app_name = "blog"

urlpatterns = [
  path("blog/", views.PostListView.as_view(), name=""),
  path("<slug:slug>/", views.PostDetailView.as_view(), name="detail"),
  #path('blog/<int:pk>', views.PostDetailView.as_view(), name='post-detail'),
   
  
] 

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import TemplateView
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import Sitemap
from blog.views import home_view, policy_view, affiliate_view
from blog.models import Post


#sitemap
class BlogSitemap(Sitemap):
    changefreq = "never"
    priority = 0.5

    def items(self):
        return Post.objects.all()

sitemaps = {'blog':BlogSitemap}

urlpatterns = [ 
    path("admin", admin.site.urls),
    path('', home_view, name='home'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path("", include("blog.urls", namespace="blog")),
    path('policy', policy_view, name='policy'),
    path("blog/affiliate", affiliate_view, name="affiliate"),
    path("", include("apis.urls", namespace="apis")),
   
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

#

apis/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

STATUS = ( (0, "Draft"), (1, "Publish") )


class Post(models.Model):
  title = models.CharField(max_length = 255)
  photo_title = models.ImageField(upload_to='images/', blank=True)
  subheading1 = models.CharField(max_length = 255, blank=True)
  body1 = models.TextField(blank=True)
  photo_body1 = models.ImageField(upload_to='images/', blank=True)
  subheading2 = models.CharField(max_length = 255, blank=True)
  body2 = models.TextField(blank=True)
  photo_body2 = models.ImageField(upload_to='images/', blank=True)
  subheading3 = models.CharField(max_length = 255, blank=True)
  body3 = models.TextField(blank=True)
  
  conclusion = models.TextField(blank=True)
  post_links = models.CharField(max_length=255, blank=True)
  slug = models.SlugField(max_length=255, unique=True)
  author = models.ForeignKey(User, on_delete=models.CASCADE)
  created = models.DateTimeField(auto_now_add=True)
  updated = models.DateTimeField(auto_now=True)
  status = models.IntegerField(choices=STATUS, default=0)
  
    
  class Meta:
    ordering = ("-created",)

  def __str__(self):
    return self.title
  
  def get_absolute_url(self):
    return reverse("blog:detail", kwargs={"slug":self.slug})

   
    
#marketing de afiliados e publicidade nativa
class TableAffiliate(models.Model):
  category_affiliate = models.CharField(max_length = 200)
  photo_affiliate = models.ImageField(upload_to='images', blank=True)
  name_affiliate = models.TextField()
  website_affiliate = models.TextField()
  commission_affiliate = models.CharField(max_length = 200)
  description_affiliate = models.CharField(max_length = 255)
  author = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self):
    return self.name_affiliate



 

apis/forms.py
from django import forms

class SearchKeyForm(forms.Form):
  search_key = forms.CharField(label = 'Insira uma palavra ou frase', max_length = 200, required=False )


class WhatsappForm(forms.Form):
  cell = forms.CharField(label = 'NÚMERO DO CELULAR', max_length = 18, required = True, strip = True, widget=forms.TextInput(attrs={'placeholder': '(00) 000000-0000'}))

apis/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from .forms import SearchKeyForm, WhatsappForm
import requests
from blog.models import Post
from django.http import HttpResponseRedirect


class SearchKeyView(TemplateView):
  
  template_name = 'apis/search_key.html'
  
  def get(self, request):
    post = Post.objects.get(pk=4)
    form = SearchKeyForm()
    return render(request, self.template_name, {'form':form, 'post':post})

  def post(self, request):
    post = Post.objects.get(pk=4)
    form = SearchKeyForm(request.POST)
    if form.is_valid():
      search_key = form.cleaned_data['search_key']

      url = "https://keywords4.p.rapidapi.com/google-topLevel-10-keywords"
      headers = {
      'content-type': "application/json",
      'x-rapidapi-host': "keywords4.p.rapidapi.com",
      'x-rapidapi-key': "C4e4A0veUwpEi3lQDOLNgWYX59sUBN86"     }

      querystring = {"search":search_key,"country":"br"}
      try:
        response = requests.request("GET", url, headers=headers, params=querystring)
        response = response.json()['googleGuggestedKeywords']
        return render(request, self.template_name, {'form':form, 'response':response,'post':post  })

      except Exception:
        return HttpResponseRedirect(self.request.path_info)
    
class WhatsappView(TemplateView):
   
  template_name = 'apis/whatsapp.html'
  
  def get(self, request):
     post = Post.objects.get(pk=2)
     form = WhatsappForm()
     return render(request, self.template_name, {'form':form,'post':post})
     

  def post(self, request):
    post = Post.objects.get(pk=2)
    form = WhatsappForm(request.POST)
    if form.is_valid():
     whatsapp = form.cleaned_data['cell']
     whatsapp = whatsapp.replace('(','').replace('-','').replace(')','')
     whatsapp = whatsapp.replace(" ","")
     whats_url = f'https://api.whatsapp.com/send?phone=+55{whatsapp}'
     whats_link = f'<i class="bx bxl-whatsapp bx-lg" style= "color:#25D366;"</i> https://api.whatsapp.com/send?phone=+55{whatsapp} <script src="https://unpkg.com/boxicons@2.1.1/dist/boxicons.js"></script>'
     return render(request, self.template_name, {'whats_link':whats_link, 'whats_url':whats_url, 'post':post})
  

blog/views.py
from django.views.generic import DetailView, ListView
from django.shortcuts import render
from .models import Post, TableAffiliate


class PostListView(ListView):
  queryset = Post.objects.filter(status=1).order_by('-created')
  model = Post
#  template_name = "blog/post_list.html"

class PostDetailView(DetailView):
  model = Post


def home_view(request, *args, **kwargs):
  return render(request, "home.html",{})
# Create your views here.


def policy_view(request, *args, **kwargs):
  return render(request, "policy.html", {})


def affiliate_view(request, *args, **kwargs):
  get_affiliate = TableAffiliate.objects.all()
  post = Post.objects.get(pk=6)
  return render(request, "blog/affiliate.html", {"get_affiliate": get_affiliate, "post":post,} )

apis/templates/apis/search_key.html
{% extends "blog/base.html" %} {% load crispy_forms_tags %} 
{% load static %}

{% block title%} {% endblock %} {% block content %}

<div class="main-content">
	<div class="container">

<h1> Buscador de palavras e frases para SEO </h1>
			<h3 class="font-weight-light"> A escolha das palavras-chave certas é fundamental para SEO. Utilize o buscador grátis e ilimitado
        de palavras-chave</h3>


<div class="container">

	<div class="row">

    <p class="fs-7 col-md-10">Insira qualquer palavra ou frase e veja as top 10 keywords mais populares </p>
	</div>

	<div class="row">

    <div class="col-sm-6">

     <div class="card">
        <div class="card-body">
    		<div class="col-md-12">
          			<h2>Gerador de palavras-chave</h2>
			<form method="post">
				{% csrf_token %} {{ form | crispy}}
				<br>
        <button type="submit" class="btn btn-primary btn-block"  value="Submit">Gerar </button><p class="text-muted"> Não guardamos nenhum dado informado</p>
</form>

</div>
      </div>
      </div></div>
         <div class="col-sm-6">
<div class="card">
        <div class="card-body">
      
   
        <h2>Top 10 palavras relacionadas</h2>

        {% for search_key in response %}
      
        <ul class="list-group list-group-flush">
       <li class="list-group-item"></li>
           
                 

   <ul class="list-group list-group-flush">
     
     <li class="list-group-item">{{search_key}}</li>
     
    
      
  {% endfor %} 
        
      </div>
   
 </div>
 </div> 
 
 </div>

</div>

<hr class="col-2 col-md-4 mb-3">

<article class="mb-4">
	<div class="container">
		<div class="row gx-4 gx-lg-5 justify-content-center">
			<div class="col-md-10">
				<h1 class="section-heading">{{post.title}}</h1>
				<img class="card-img-top" src="{{ post.photo_title.url }}" alt="{{post.title}}">

<h2> {{post.subheading1}} </h2>
                      
                        <p> {{post.body1|linebreaks}} </p>
                        <h2 class="section-heading">{{post.subheading2}}</h2>
                        <img class="card-img-top" src="{{ post.photo_body1.image_url|default_if_none:'' }}" alt="">
                        
                        
                        <p>{{post.body2|linebreaks}}</p>
                        <blockquote class="blockquote"></blockquote>
                         
                        <h2 class="section-heading">{{post.subheading3}}</h2>
                        <img class="card-img-top" src="{{ post.photo_body2.image_url.url|default_if_none:'' }}" alt="">
                        <p>{{post.body3|linebreaks}}</p>
                        
                        <span class="caption text-muted"></span>
                         <img class="card-img-top" src="{{ post.photo_body3.image_url.url|default_if_none:'' }}" alt="">
                        <p class="section-heading">{{post.conclusion|linebreaks }}</p>
                        
                          <h4>- Publicado em: {{post.created}} -</h4>
                          <h4>Quer saber mais? Confira nosso 
                          <a href="{% url 'blog:' %}"<h5>Blog </h5> </a>
                            
                        </p>
                    </div>
                </div>
            </div>
        </article>
      </div>
    </div>

<script src="{% static 'apis.js' %}"></script>
{% endblock %}

apis/templates/apis/whatsapp.html
{% extends "blog/base.html" %} {% load crispy_forms_tags %} 
{% load static %}

{% block title%} {% endblock %} {% block content %}

<div class="main-content">
	<div class="container">

<h1> Gerador de botão de whatsapp grátis <i class="bx bxl-whatsapp"></i></h1>
			<h3 class="font-weight-light"> Acesse facilmente o contato dos visitantes do seu site diretamente pelo link do Whatsapp</h3>


<div class="container">

	<div class="row">

    <p class="fs-7 col-md-10">Você cria um botão de WhatsApp, instala no seu site e fica pronto para receber mensagens de pessoas interessadas nas suas ofertas</p>
	</div>

	<div class="row">

    <div class="col-sm-6">

     <div class="card">
        <div class="card-body">
    		<div class="col-md-12">
          			<h2>Gerador de botão do whatsapp</h2>
			<form method="post">
				{% csrf_token %} {{ form | crispy}}
				<br>
        <button type="submit" class="btn btn-success btn-block"  value="Submit">Gerar <i class="bx bxl-whatsapp"></i></button><p class="text-muted"> Não guardamos nenhum dado informado</p>
</form>

</div>
      </div>
      </div></div>
         <div class="col-sm-6">
<div class="card">
        <div class="card-body">
      
   
        <h2></h2>

        

   <ul class="list-group list-group-flush">
     <li class="list-group-item"><i class="bx bxl-whatsapp bx-lg" style= "color:#25D366;"></i><i class="bx bxs-file-html bx-lg" style= "color:#25D366;"></i></li>
     <li class="list-group-item"><code>{{whats_link}}</code></li>
     <li class="list-group-item"><i class="bx bx-link-alt bx-md" style= "color:#25D366;"></i></li>
     
  <li class="list-group-item"><code>{{whats_url}}</code></li>
      
            
        
      </div>
   
 </div>
 </div> 
 
 </div>

</div>

<hr class="col-2 col-md-4 mb-3">

<article class="mb-4">
	<div class="container">
		<div class="row gx-4 gx-lg-5 justify-content-center">
			<div class="col-md-10">
				<h1 class="section-heading">{{post.title}}</h1>
				<img class="card-img-top" src="{{ post.photo_title.url }}" alt="{{post.title}}">

<h2> {{post.subheading1}} </h2>
                      
                        <p> {{post.body1|linebreaks}} </p>
                        <h2 class="section-heading">{{post.subheading2}}</h2>
                        <img class="card-img-top" src="{{ post.photo_body1.image_url|default_if_none:'' }}" alt="">
                        
                        
                        <p>{{post.body2|linebreaks}}</p>
                        <blockquote class="blockquote"></blockquote>
                         
                        <h2 class="section-heading">{{post.subheading3}}</h2>
                        <img class="card-img-top" src="{{ post.photo_body2.image_url.url|default_if_none:'' }}" alt="">
                        <p>{{post.body3|linebreaks}}</p>
                        
                        <span class="caption text-muted"></span>
                         <img class="card-img-top" src="{{ post.photo_body3.image_url.url|default_if_none:'' }}" alt="">
                        <p class="section-heading">{{post.conclusion|linebreaks }}</p>
                        
                          <h4>- Publicado em: {{post.created}} -</h4>
                          <h4>Quer saber mais? Confira nosso 
                          <a href="{% url 'blog:' %}"<h5>Blog </h5> </a>
                            
                        </p>
                    </div>
                </div>
            </div>
        </article>
      </div>
    </div>

<script src="{% static 'apis.js' %}"></script>
{% endblock %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
	 crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'blog/style.css' %}" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css" />
	<link rel="icon" href="{% static 'favicon.ico' %}"/>
	<title>DIGITIMES - Ferramentas essenciais para negócios online</title>
	<!-- Open Graph / Facebook -->
<meta property="og:type" content="website">
<meta property="og:url" content="https://digitimes.com.br/">
<meta property="og:title" content="DT | DIGITIMES - Ferramentas essenciais para negócios online">
<meta property="og:description" content="Marketing Digital para quem tem pressa!
Blogs, tutoriais e ferramentas para marketing digital e negócios online">

<!-- Twitter -->
<meta property="twitter:card" content="summary_large_image">
<meta property="twitter:url" content="https://digitimes.com.br/">
<meta property="twitter:title" content="DT | DIGITIMES - Ferramentas essenciais para negócios online">
<meta property="twitter:description" content="Marketing Digital para quem tem pressa!
Blogs, tutoriais e ferramentas para marketing digital e negócios online">
</head>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<div class="container-fluid offset-md-1">
		<a class="navbar-brand" href="{% url 'home' %}">DIGITIMES</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarsExample07">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'blog:' %}">Blog e Tutoriais <span class="sr-only"></span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'affiliate' %}">Canais de venda e publicidade<span class="sr-only"></span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'apis:search_key' %}">Palavra-chave<span class="sr-only"></span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'apis:whatsapp' %}">Botão Whatsapp <i class="bx bxl-whatsapp"> </i><span class="sr-only"></span></a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
<body>
	<main> 


	
    
     {%block content %} {% endblock content %} 
     
     
     
 <div class="footer-basic">
       <section class="footers bg-light pt-5 pb-3">
   <div class="container pt-6">
       <div class="row">
           <div class="col-xs-12 col-sm-6 col-md-4 footers-one">
    		    <div class="footers-logo">
    		        <h5>Sobre nós</h5>
    		    </div>
    		    <div class="footers-info mt-6">
    		        <p>DIGITIMES é um site gratuito de recursos de Marketing e Negócios Online. A DIGITIMES foi fundada em 2021. O principal objetivo deste site é fornecer tutoriais, dicas, cursos, ferramentas e outros recursos de qualidade que permitam a qualquer pessoa trabalhar online e dominar o marketing digital com base em estudos de caso reais e pesquisas aprofundadas.</p>
    		    </div>
    		     
    		</div>
    	   <div class="col-xs-12 col-sm-6 col-md-4 footers-two">
    		    <h5>Nossos sites </h5>
    		    <ul class="list-unstyled">
    			 <li><a href="{% url 'blog:' %}">Blog e tutoriais</a></li>
           </ul>
    		</div>
    	   <div class="col-xs-12 col-sm-6 col-md-2 footers-three">
    		    <h5>Nossos links </h5>
    		    <ul class="list-unstyled">
    			 <li><a href="{% url 'policy' %}">Política de Privacidade</a></li>
    			 <li><a href="{% url 'policy' %}">Termos e Condições</a></li>
    			 <!-- <li><a href="about.html">mapa do site</a></li> -->
    			 <li><a href="{% url 'policy' %}">Política de Cookies</a></li>
    			 <li><a href="{% url 'policy' %}"></a></li>
    			</ul>
    		</div>

       </div>
   </div>
</section>
    </div>
    <!-- Latest compiled and minified JavaScript -->
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-0158TN4LLS"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-0158TN4LLS');
</script>



</body>

</html>

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %} {% block title %} {{post.title}} {% endblock %} {% block content %}
<div class="main-content">
	<div class="container">

<article>

			<div class="col-md-10">
				<h1 class="section-heading">{{post.title}}</h1>
				<img class="card-img-top" src="{{ post.photo_title.url }}" alt="{{post.title}}">

<h2> {{post.subheading1}} </h2>
                      
                        <p> {{post.body1|linebreaks}} </p>
                        <h2 class="section-heading">{{post.subheading2}}</h2>
                        {% if post.photo_body1 %}
                        <img class="card-img-top" src="{{ post.photo_body1.url }}" alt="">
                        {% else %}
                        {% endif %}
                        
                        
                        <p>{{post.body2|linebreaks}}</p>
                        <blockquote class="blockquote"></blockquote>
                         
                        <h2 class="section-heading">{{post.subheading3}}</h2>
                         {% if post.photo_body2 %}
                        <img class="card-img-top" src="{{ post.photo_body2.url }}" alt="">
                         {% else %}
                        {% endif %}
                        <p>{{post.body3|linebreaks}}</p>
                        
                        <span class="caption text-muted"></span>
                        
                         
                       
                        <p class="section-heading">{{post.conclusion|linebreaks }}</p>
                        
                          <h4>- Publicado em: {{post.created}} -</h4>
                          <h4>Links adicionais:</h4><a href= "{{post.post_links.url}}">
                          <h5>{{post.post_links}}</h5> </a>
                            
                        </p>
                    </div>
            
        </article>
</div></div>

{% endblock %}

blog/templates/home.html
{% extends "blog/base.html" %} {% block content %}
<div class="row">

<div class="container-fluid offset-md-1 col-8">

<h1> Marketing digital para quem tem pressa!</h1>
<h3 class="font-weight-light"> Ferramentas essenciais para negócios online</h3>
 
<div class="row">
<div class="col-md-4">
    <div class="card p-3 mb-2">
        <div class="d-flex justify-content-between">
            <div class="d-flex flex-row align-items-center">
                <div class="icon"> <i class="bx bxl-blogger"></i> </div>
            <div class="ms-2 c-details">
                <h6 class="mb-0"> Conhecimento</h6> 
            </div>
        </div>
        <div class="badge"> <span>Blog</span> </div>
    </div>
    <div class="mt-5">
       <a href="{% url 'blog:' %}"><h3 class="heading"><br>Blogs e Tutoriais sobre negócios online</h3></a>
        <div class="mt-5">
            <div class="progress">
                <div class="progress-bar bg-info" role="progressbar" style="width: 100%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <div class="mt-3"> <span class="text2"><i class="bx bx-like"></i>580<span class="text2"></span></span> </div>
        </div>
    </div>
</div>
</div>
<div class="col-md-4">
<div class="card p-3 mb-2">
    <div class="d-flex justify-content-between">
        <div class="d-flex flex-row align-items-center">
            <div class="icon"> <i class="bx bxl-google"></i> </div>
            <div class="ms-2 c-details">
                <h6 class="mb-0">Planejador de Palavras-chave grátis</h6> 
            </div>
        </div>
        <div class="badge"> <span>SEO</span> </div>
    </div>
    <div class="mt-5">
      <a href="{% url 'apis:search_key' %}">
        <h3 class="heading">Encontre as palavras-chave mais buscadas no google para otimizar seu SEO   <br></h3></a>
        <div class="mt-5">
            <div class="progress">
                <div class="progress-bar bg-info" role="progressbar" style="width: 100%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <div class="mt-3"> <span class="text2"><i class="bx bx-like">853</i></span> </div>
        </div>
    </div>
</div>
</div>
<div class="col-md-4">
<div class="card p-3 mb-2">
    <div class="d-flex justify-content-between">
        <div class="d-flex flex-row align-items-center">
            <div class="icon"> <i class="bx bxl-instagram-alt"></i> </div>
            <div class="ms-2 c-details">
                <h6 class="mb-0"> Influensearch grátis </h6> 
            </div>
        </div>
        <div class="badge"> <span>Marketing</span> </div>
    </div>
    <div class="mt-5">
        <h3 class="heading">Pesquisador de Influenciadores <br>Digitais (em breve)</h3>
        <div class="mt-5">
            <div class="progress">
                <div class="progress-bar bg-info" role="progressbar" style="width: 100%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <div class="mt-3"> <span class="text2"><i class="bx bx-like"></i></span> </div>
        </div>
    </div>
    
</div>
</div>
<div class="col-md-4">
<div class="card p-3 mb-2">
    <div class="d-flex justify-content-between">
        <div class="d-flex flex-row align-items-center">
            <div class="icon"> <i class="bx bx-table"></i> </div>
            <div class="ms-2 c-details">
                <h6 class="mb-0"> Divulgadores de conteúdo, publicidade e canais de vendas</h6> 
            </div>
        </div>
        <div class="badge"> <span>Marketing</span> </div>
    </div>
    <div class="mt-5"><a href="{% url 'affiliate' %}">
        <h3 class="heading">Comparativo de Marketing de afiliados, native ads e Marketplaces </h3></a>
        <div class="mt-5">
            <div class="progress">
                <div class="progress-bar bg-info" role="progressbar" style="width: 100%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <div class="mt-3"> <span class="text2"><i class="bx bx-like"></i>120</span> </div>
        </div>
    </div>
    
</div>
</div>
<div class="col-md-4">
<div class="card p-3 mb-2">
    <div class="d-flex justify-content-between">
        <div class="d-flex flex-row align-items-center">
            <div class="icon"> <i class="bx bxl-whatsapp"></i> </div>
            <div class="ms-2 c-details">
                <h6 class="mb-0"> Gerador de botão Whatsapp</h6> 
            </div>
        </div>
        <div class="badge"> <span>Marketing</span> </div>
    </div>
    <div class="mt-5">
      <a href="{% url 'apis:whatsapp' %}">
        <h3 class="heading">Gerador de botão Whatsapp</h3></a>
        <div class="mt-5">
            <div class="progress">
                <div class="progress-bar bg-info" role="progressbar" style="width: 100%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <div class="mt-3"> <span class="text2"><i class="bx bx-like"></i></span> </div>
        </div>
    </div>
    
</div>
</div>
<div class="col-md-4">
<div class="card p-3 mb-2">
    <div class="d-flex justify-content-between">
        <div class="d-flex flex-row align-items-center">
            <div class="icon"> <i class="bx bx-file"></i> </div>
            <div class="ms-2 c-details">
                <h6 class="mb-0">Gerador de Documentos grátis</h6> 
            </div>
        </div>
        <div class="badge"> <span>Jurídico</span> </div>
    </div>
    <div class="mt-5">
      <h3 class="heading">Gerador de Políticas  <br>Privacidade, LGPD, Cookies, Termos e Condições e outros (em breve)</h3>
        <div class="mt-5">
            <div class="progress">
                <div class="progress-bar bg-info" role="progressbar" style="width: 100%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <div class="mt-3"> <span class="text2"><i class="bx bx-like"></i></span> </div>
        </div>
    </div>

</div>

</div>

</div>

</div>
{% block sidebar %}
{% include "blog/sidebar.html" %}
{% endblock %}
</div>

</main>


{% endblock  %}  